export const LOGIN_REQUEST = "LOGIN_REQUEST"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAIL = "LOGIN_FAIL"
export const REGISTER_SUCCESS = "REGISTER_SUCCESS"
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS"
export const STUDENT_SUCCESS = "STUDENT_SUCCESS"

export const ATTENDENCE_SUCCESS = "ATTENDENCE_SUCCESS"
export const CREATE_ATTENDENCE_SUCCESS = "CREATE_ATTENDENCE_SUCCESS"



